import { NextResponse } from "next/server";
import { headers } from "next/headers";
import ExcelJS from "exceljs";
import { getCurrentUser, getClientIp } from "@/shared/auth/session";
import { recordAudit } from "@/shared/audit/audit";
import { getReport, buildReportView } from "@/modules/reports/definitions";

/** Report export endpoint (SDS Doc 15 Ch8): CSV/XLSX with generation metadata. */
export async function GET(
  request: Request,
  { params }: { params: Promise<{ key: string }> },
): Promise<Response> {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Authentication required." }, { status: 401 });
  if (!user.permissions.has("reports.export")) {
    return NextResponse.json({ error: "Permission denied." }, { status: 403 });
  }
  const { key } = await params;
  const report = getReport(key);
  if (!report) return NextResponse.json({ error: "Report not found." }, { status: 404 });

  const url = new URL(request.url);
  const format = url.searchParams.get("format") === "xlsx" ? "xlsx" : "csv";
  // Carry any report filters from the query string into the export.
  const filters: Record<string, string> = {};
  for (const [param, value] of url.searchParams.entries()) {
    if (param !== "format" && value) filters[param] = value;
  }
  const queried = await report.run(user, filters);
  // Export what the filters select, not the unfiltered report: an operator who
  // narrows the screen and then exports expects the same rows. Paging is
  // deliberately not applied - an export is the whole filtered set.
  const view = buildReportView(report, queried, filters, 1, Number.MAX_SAFE_INTEGER);
  const result = { headers: view.headers, rows: view.filteredRows };
  const generatedAt = new Date();

  const requestHeaders = await headers();
  await recordAudit(
    {
      actorUserId: user.userId,
      actorPersonId: user.personId,
      actorLabel: user.username,
      companyId: user.companyId,
      ipAddress: getClientIp(requestHeaders),
      userAgent: requestHeaders.get("user-agent")?.slice(0, 512) ?? null,
    },
    {
      module: "reports",
      eventType: "report.exported",
      action: `Exported report "${report.name}" as ${format.toUpperCase()} (${result.rows.length} row(s))`,
      targetType: "report",
      targetLabel: report.key,
    },
  );

  const stamp = generatedAt.toISOString().slice(0, 10);
  if (format === "xlsx") {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = "Axivo";
    const sheet = workbook.addWorksheet(report.name.slice(0, 31));
    sheet.addRow([`${report.name} generated by ${user.username} at ${generatedAt.toISOString()}`]);
    sheet.addRow([]);
    const headerRow = sheet.addRow(result.headers);
    headerRow.font = { bold: true };
    for (const row of result.rows) sheet.addRow(row);
    sheet.columns.forEach((column) => {
      column.width = 24;
    });
    const buffer = Buffer.from(await workbook.xlsx.writeBuffer());
    return new Response(new Uint8Array(buffer), {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": `attachment; filename="axivo-${report.key}-${stamp}.xlsx"`,
        "Cache-Control": "private, no-store",
      },
    });
  }

  const escape = (value: string) => (/[",\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value);
  const csv = [
    `# ${report.name} generated by ${user.username} at ${generatedAt.toISOString()}`,
    result.headers.join(","),
    ...result.rows.map((row) => row.map(escape).join(",")),
  ].join("\r\n");
  return new Response(csv, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="axivo-${report.key}-${stamp}.csv"`,
      "Cache-Control": "private, no-store",
    },
  });
}
