#!/usr/bin/env bash
# =============================================================================
# Axivo installer - self-host on a Linux VM.
#
#   curl -fsSL https://raw.githubusercontent.com/virginpixel/axivo/main/install.sh | sudo bash
#
# Pulls prebuilt images from GHCR (no build toolchain needed), generates and
# PERSISTS secrets once, and starts the stack. Safe to re-run: existing secrets
# and data are preserved (the encryption key is never regenerated, or stored
# credentials would become unreadable).
# =============================================================================
set -euo pipefail

REPO_OWNER="virginpixel"
REPO_NAME="axivo"
INSTALL_DIR="${AXIVO_INSTALL_DIR:-/opt/axivo}"
COMPOSE="docker-compose.prod.yml"

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!\033[0m  %s\n' "$*"; }
die()  { printf '\033[1;31mx\033[0m  %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Please run as root (use sudo)."

# --- Prerequisites --------------------------------------------------------
command -v curl >/dev/null   || die "curl is required."
command -v openssl >/dev/null || die "openssl is required."

if ! command -v docker >/dev/null; then
  log "Docker not found. Installing via get.docker.com ..."
  curl -fsSL https://get.docker.com | sh
fi
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 plugin is required."
systemctl enable --now docker >/dev/null 2>&1 || true

# --- Resolve which version to install -------------------------------------
# AXIVO_VERSION env overrides; otherwise use the latest published release.
REF="main"
if [ -n "${AXIVO_VERSION:-}" ]; then
  VERSION="$AXIVO_VERSION"
  REF="$AXIVO_VERSION"
else
  VERSION="$(curl -fsSL "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/releases/latest" 2>/dev/null \
             | grep -oP '"tag_name":\s*"\K[^"]+' || true)"
  if [ -n "$VERSION" ]; then
    REF="$VERSION"
  else
    warn "No published release found; using the 'latest' image tag from the main branch."
    VERSION="latest"
    REF="main"
  fi
fi
log "Installing Axivo ${VERSION}"

# --- Fetch deploy assets (compose + nginx config) at the chosen ref -------
mkdir -p "$INSTALL_DIR"
RAW="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/${REF}"
for f in "deploy/${COMPOSE}" "deploy/Caddyfile"; do
  log "Fetching ${f}"
  curl -fsSL "${RAW}/${f}" -o "${INSTALL_DIR}/$(basename "$f")" \
    || die "Could not download ${f} from ${REF}. Is the repo public and the ref valid?"
done

cd "$INSTALL_DIR"

# --- Secrets: generate once, preserve forever -----------------------------
FRESH_INSTALL=1
if [ -f .env ]; then
  FRESH_INSTALL=0
  log "Existing install detected - preserving secrets and data."
  # shellcheck disable=SC1091
  set -a; . ./.env; set +a
fi

gen() { openssl rand -hex 32; }
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(gen)}"
SESSION_SECRET="${SESSION_SECRET:-$(gen)}"
ENCRYPTION_KEY="${ENCRYPTION_KEY:-$(gen)}"
TOKEN_SIGNING_KEY="${TOKEN_SIGNING_KEY:-$(gen)}"

# --- Prompt for host details (only on a fresh install) --------------------
# No administrator is seeded: the first person to open the site creates the
# organization and the founding admin through the setup screen.
DEFAULT_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
if [ "$FRESH_INSTALL" -eq 1 ]; then
  read -rp "Hostname or IP to access Axivo at [${DEFAULT_IP}]: " AXIVO_HOST </dev/tty || true
  AXIVO_HOST="${AXIVO_HOST:-$DEFAULT_IP}"
else
  # Keep whatever the previous .env had.
  AXIVO_HOST="${AXIVO_HOST:-${APP_HOST:-$DEFAULT_IP}}"
fi

# TLS is layered on in a later phase; for now the stack serves over HTTP.
APP_URL="${APP_URL:-http://${AXIVO_HOST}}"

# --- Write .env -----------------------------------------------------------
umask 077
cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit.
NODE_ENV=production
AXIVO_VERSION=${VERSION}
APP_HOST=${AXIVO_HOST}
APP_URL=${APP_URL}
PORT=3000

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://axivo:${POSTGRES_PASSWORD}@postgres:5432/axivo?schema=public
REDIS_URL=redis://redis:6379

SESSION_SECRET=${SESSION_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
TOKEN_SIGNING_KEY=${TOKEN_SIGNING_KEY}

STORAGE_PATH=/var/lib/axivo/storage
EOF

# --- Pull and start -------------------------------------------------------
log "Pulling images ..."
docker compose -f "$COMPOSE" pull
log "Starting Axivo ..."
docker compose -f "$COMPOSE" up -d

echo
log "Axivo is starting at: ${APP_URL}"
if [ "$FRESH_INSTALL" -eq 1 ]; then
  echo "    Open that address in a browser to create your organization and the"
  echo "    first administrator account."
fi
echo "    Install dir:    ${INSTALL_DIR}"
