import { requirePermission } from "@/shared/auth/guard";
import { db } from "@/shared/db";
import { PageHeader, StatCard, Pagination } from "@/shared/ui/page";
import { Table, THead, TBody, TR, TH, TD, EmptyState } from "@/shared/ui/table";
import { StatusBadge } from "@/shared/ui/badge";
import { Input, Select } from "@/shared/ui/input";
import { formatDateTime } from "@/shared/utils";
import { NotificationRowActions, TemplateDialog } from "./notification-ui";
import type { Prisma, NotificationStatus } from "@prisma/client";

export const metadata = { title: "Notifications" };
export const dynamic = "force-dynamic";

const STATUSES: NotificationStatus[] = ["QUEUED", "SENDING", "DELIVERED", "FAILED", "CANCELLED", "EXPIRED"];

/** Notification monitoring and templates (SDS Doc 14 Ch8). */
export default async function NotificationsPage({
  searchParams,
}: {
  searchParams: Promise<{ q?: string; status?: string; page?: string }>;
}) {
  const { user } = await requirePermission("notifications.view");
  const params = await searchParams;
  const q = params.q?.trim() ?? "";
  const page = Math.max(1, Number(params.page) || 1);
  const pageSize = 25;
  const isGlobalAdmin = user.systemRoleKey === "SYSTEM_ADMINISTRATOR";
  const canManage = user.permissions.has("notifications.manage");
  const companyScope = isGlobalAdmin ? {} : { OR: [{ companyId: user.companyId }, { companyId: null }] };

  const where: Prisma.NotificationWhereInput = {
    ...companyScope,
    ...(params.status && STATUSES.includes(params.status as NotificationStatus)
      ? { status: params.status as NotificationStatus }
      : {}),
    ...(q
      ? {
          OR: [
            { subject: { contains: q, mode: "insensitive" } },
            { eventType: { contains: q, mode: "insensitive" } },
            { recipients: { some: { email: { contains: q, mode: "insensitive" } } } },
          ],
        }
      : {}),
  };

  const [rows, total, statusCounts, templates] = await Promise.all([
    db.notification.findMany({
      where,
      orderBy: { createdAt: "desc" },
      skip: (page - 1) * pageSize,
      take: pageSize,
      include: { recipients: true },
    }),
    db.notification.count({ where }),
    db.notification.groupBy({ by: ["status"], _count: true }),
    db.notificationTemplate.findMany({
      where: { isActive: true },
      orderBy: { key: "asc" },
    }),
  ]);
  const counts = Object.fromEntries(statusCounts.map((entry) => [entry.status, entry._count]));
  const pageCount = Math.max(1, Math.ceil(total / pageSize));

  return (
    <div>
      <PageHeader
        title="Notifications"
        description="Email delivery queue, history and templates. Delivery history is immutable."
      />

      <div className="mb-5 grid grid-cols-2 gap-4 lg:grid-cols-4">
        <StatCard label="Queued" value={counts.QUEUED ?? 0} tone="info" />
        <StatCard label="Delivered" value={counts.DELIVERED ?? 0} tone="success" />
        <StatCard label="Failed" value={counts.FAILED ?? 0} tone={(counts.FAILED ?? 0) > 0 ? "destructive" : "default"} />
        <StatCard label="Cancelled / expired" value={(counts.CANCELLED ?? 0) + (counts.EXPIRED ?? 0)} />
      </div>

      <form method="get" className="mb-4 flex flex-wrap items-end gap-2">
        <Input name="q" defaultValue={q} placeholder="Search subject, event, recipient…" className="w-full sm:w-72" aria-label="Search notifications" />
        <Select name="status" defaultValue={params.status ?? ""} className="w-full sm:w-40" aria-label="Filter by status">
          <option value="">All statuses</option>
          {STATUSES.map((status) => (
            <option key={status} value={status}>{status}</option>
          ))}
        </Select>
        <button type="submit" className="h-9 rounded-md border bg-card px-4 text-sm hover:bg-accent">Filter</button>
      </form>

      {rows.length === 0 ? (
        <EmptyState title="No notifications" description="Emails generated by workflows and reminders appear here with delivery status." />
      ) : (
        <>
          <Table>
            <THead>
              <TR>
                <TH>Subject</TH><TH>Event</TH><TH>Recipients</TH><TH>Attempts</TH><TH>Created</TH><TH>Status</TH>
                {canManage ? <TH className="text-right">Actions</TH> : null}
              </TR>
            </THead>
            <TBody>
              {rows.map((notification) => (
                <TR key={notification.id}>
                  <TD className="max-w-72">
                    <span className="block truncate font-medium">{notification.subject}</span>
                    {notification.lastError ? (
                      <span className="block truncate text-xs text-destructive">{notification.lastError}</span>
                    ) : null}
                  </TD>
                  <TD className="text-xs">{notification.eventType}</TD>
                  <TD className="max-w-52 truncate text-xs">
                    {notification.recipients.map((recipient) => recipient.email).join(", ")}
                  </TD>
                  <TD>{notification.attempts}</TD>
                  <TD className="whitespace-nowrap text-xs">{formatDateTime(notification.createdAt)}</TD>
                  <TD><StatusBadge status={notification.status} /></TD>
                  {canManage ? (
                    <TD className="text-right">
                      <NotificationRowActions notificationId={notification.id} status={notification.status} />
                    </TD>
                  ) : null}
                </TR>
              ))}
            </TBody>
          </Table>
          <Pagination
            page={page}
            pageCount={pageCount}
            total={total}
            buildHref={(p) => {
              const search = new URLSearchParams();
              if (q) search.set("q", q);
              if (params.status) search.set("status", params.status);
              search.set("page", String(p));
              return `/notifications?${search.toString()}`;
            }}
          />
        </>
      )}

      <section aria-label="Notification templates" className="mt-8">
        <h2 className="mb-3 text-base font-semibold">Templates</h2>
        <Table>
          <THead>
            <TR>
              <TH>Key</TH><TH>Name</TH><TH>Type</TH><TH>Subject</TH><TH>Version</TH>
              {canManage ? <TH className="text-right">Actions</TH> : null}
            </TR>
          </THead>
          <TBody>
            {templates.map((template) => (
              <TR key={template.id}>
                <TD className="font-mono text-xs">{template.key}</TD>
                <TD>{template.name}</TD>
                <TD className="text-xs">{template.type}</TD>
                <TD className="max-w-72 truncate text-xs">{template.subject}</TD>
                <TD>v{template.version}</TD>
                {canManage ? (
                  <TD className="text-right">
                    <TemplateDialog
                      template={{
                        key: template.key,
                        name: template.name,
                        type: template.type,
                        subject: template.subject,
                        body: template.body,
                        variables: (template.variables as string[] | null) ?? [],
                      }}
                    />
                  </TD>
                ) : null}
              </TR>
            ))}
          </TBody>
        </Table>
      </section>
    </div>
  );
}
