import PDFDocument from "pdfkit";

/**
 * Server-side PDF generation (SDS Doc 02 Ch2). Generated documents (handover
 * forms, clearance forms, request summaries, disposal forms) inherit the
 * configured branding (Doc 03 Ch9).
 */

export interface PdfBranding {
  systemName: string;
  companyName?: string;
  primaryColor?: string;
}

export interface PdfSection {
  heading?: string;
  paragraphs?: string[];
  /** Two-column label/value rows. */
  fields?: { label: string; value: string }[];
  /** Table with headers and rows. */
  table?: { headers: string[]; rows: string[][] };
}

export interface PdfDefinition {
  title: string;
  subtitle?: string;
  branding: PdfBranding;
  sections: PdfSection[];
  footerNote?: string;
}

export async function renderPdf(definition: PdfDefinition): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const primary = definition.branding.primaryColor ?? "#1d4ed8";

    // Header
    doc.fillColor(primary).fontSize(20).font("Helvetica-Bold").text(definition.branding.systemName);
    if (definition.branding.companyName) {
      doc.fillColor("#444444").fontSize(10).font("Helvetica").text(definition.branding.companyName);
    }
    doc.moveDown(0.5);
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor(primary)
      .lineWidth(2)
      .stroke();
    doc.moveDown(1);

    doc.fillColor("#111111").fontSize(16).font("Helvetica-Bold").text(definition.title);
    if (definition.subtitle) {
      doc.fillColor("#555555").fontSize(10).font("Helvetica").text(definition.subtitle);
    }
    doc.moveDown(1);

    for (const section of definition.sections) {
      if (section.heading) {
        doc.moveDown(0.5);
        doc.fillColor(primary).fontSize(12).font("Helvetica-Bold").text(section.heading);
        doc.moveDown(0.3);
      }
      if (section.paragraphs) {
        for (const paragraph of section.paragraphs) {
          doc.fillColor("#222222").fontSize(10).font("Helvetica").text(paragraph, { lineGap: 2 });
          doc.moveDown(0.3);
        }
      }
      if (section.fields) {
        for (const field of section.fields) {
          const y = doc.y;
          doc.fillColor("#666666").fontSize(9).font("Helvetica-Bold").text(field.label, 50, y, { width: 160 });
          doc.fillColor("#111111").fontSize(10).font("Helvetica").text(field.value || "—", 220, y, { width: 320 });
          doc.moveDown(0.4);
        }
      }
      if (section.table) {
        renderTable(doc, section.table, primary);
      }
    }

    if (definition.footerNote) {
      doc.moveDown(1.5);
      doc.fillColor("#777777").fontSize(8).font("Helvetica-Oblique").text(definition.footerNote);
    }

    // Page numbers + generation timestamp
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i += 1) {
      doc.switchToPage(i);
      doc
        .fillColor("#999999")
        .fontSize(8)
        .font("Helvetica")
        .text(
          `Generated by ${definition.branding.systemName} on ${new Date().toISOString().replace("T", " ").slice(0, 16)} UTC — Page ${i + 1} of ${range.count}`,
          50,
          800,
          { width: 495, align: "center" },
        );
    }
    doc.end();
  });
}

function renderTable(
  doc: PDFKit.PDFDocument,
  table: { headers: string[]; rows: string[][] },
  primary: string,
): void {
  const startX = 50;
  const usableWidth = 495;
  const columnWidth = usableWidth / table.headers.length;
  const rowHeight = 20;

  const drawRow = (cells: string[], y: number, isHeader: boolean) => {
    if (isHeader) {
      doc.rect(startX, y, usableWidth, rowHeight).fill(primary);
    }
    cells.forEach((cell, index) => {
      doc
        .fillColor(isHeader ? "#ffffff" : "#222222")
        .fontSize(9)
        .font(isHeader ? "Helvetica-Bold" : "Helvetica")
        .text(cell, startX + index * columnWidth + 4, y + 5, {
          width: columnWidth - 8,
          height: rowHeight,
          ellipsis: true,
        });
    });
  };

  let y = doc.y;
  drawRow(table.headers, y, true);
  y += rowHeight;
  for (const row of table.rows) {
    if (y > 760) {
      doc.addPage();
      y = 50;
      drawRow(table.headers, y, true);
      y += rowHeight;
    }
    doc.rect(startX, y, usableWidth, rowHeight).strokeColor("#dddddd").lineWidth(0.5).stroke();
    drawRow(row, y, false);
    y += rowHeight;
  }
  doc.y = y + 10;
  doc.x = startX;
}
