import PDFDocument from "pdfkit";
import { formatDateTimeWithZone } from "@/shared/utils";

/**
 * Server-side PDF generation (SDS Doc 02 Ch2). Generated documents (handover
 * forms, clearance forms, request summaries, disposal forms) inherit the
 * configured branding (Doc 03 Ch9).
 */

export interface PdfBranding {
  systemName: string;
  companyName?: string;
  primaryColor?: string;
  /** Optional header logos (PNG/JPG bytes) positioned left / center / right. */
  logos?: { left?: Buffer; center?: Buffer; right?: Buffer };
}

export interface PdfSection {
  heading?: string;
  paragraphs?: string[];
  /** Two-column label/value rows. */
  fields?: { label: string; value: string }[];
  /** Table with headers and rows. */
  table?: { headers: string[]; rows: string[][] };
}

export interface PdfDefinition {
  title: string;
  subtitle?: string;
  branding: PdfBranding;
  sections: PdfSection[];
  footerNote?: string;
}

export async function renderPdf(definition: PdfDefinition): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const primary = definition.branding.primaryColor ?? "#1d4ed8";

    // Optional logo band (left / center / right).
    const logos = definition.branding.logos;
    if (logos && (logos.left || logos.center || logos.right)) {
      const bandY = doc.y;
      const h = 44;
      const w = 120;
      const place = (buffer: Buffer | undefined, x: number, align: "left" | "center" | "right") => {
        if (!buffer) return;
        try {
          doc.image(buffer, x, bandY, { fit: [w, h], align, valign: "center" } as never);
        } catch {
          /* ignore invalid image bytes */
        }
      };
      place(logos.left, 50, "left");
      place(logos.center, (595 - w) / 2, "center");
      place(logos.right, 545 - w, "right");
      doc.y = bandY + h + 6;
    }

    // Header: the document is the form, so its own title leads. The product
    // name and the company used to sit above it, which made every printed form
    // announce the software before saying what it was; the company now appears
    // where it belongs, among the employee's details.
    doc.fillColor("#111111").fontSize(18).font("Helvetica-Bold").text(definition.title, {
      align: "center",
    });
    if (definition.subtitle) {
      doc.moveDown(0.2);
      doc.fillColor("#555555").fontSize(10).font("Helvetica").text(definition.subtitle, {
        align: "center",
      });
    }
    doc.moveDown(0.5);
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor(primary)
      .lineWidth(1.5)
      .stroke();
    doc.moveDown(1);

    for (const section of definition.sections) {
      if (section.heading) {
        doc.moveDown(0.5);
        doc.fillColor(primary).fontSize(12).font("Helvetica-Bold").text(section.heading);
        doc.moveDown(0.3);
      }
      if (section.paragraphs) {
        for (const paragraph of section.paragraphs) {
          doc.fillColor("#222222").fontSize(10).font("Helvetica").text(paragraph, { lineGap: 2 });
          doc.moveDown(0.3);
        }
      }
      if (section.fields) {
        for (const field of section.fields) {
          const y = doc.y;
          doc.fillColor("#666666").fontSize(9).font("Helvetica-Bold").text(field.label, 50, y, { width: 160 });
          doc.fillColor("#111111").fontSize(10).font("Helvetica").text(field.value || "None", 220, y, { width: 320 });
          doc.moveDown(0.4);
        }
      }
      if (section.table) {
        renderTable(doc, section.table, primary);
      }
    }

    if (definition.footerNote) {
      doc.moveDown(1.5);
      doc.fillColor("#777777").fontSize(8).font("Helvetica-Oblique").text(definition.footerNote);
    }

    // Page numbers + generation timestamp. The footer sits below the normal text
    // area, so the bottom margin is temporarily zeroed: otherwise PDFKit treats
    // it as overflow and appends a blank page.
    const range = doc.bufferedPageRange();
    const generatedAt = formatDateTimeWithZone(new Date());
    for (let i = range.start; i < range.start + range.count; i += 1) {
      doc.switchToPage(i);
      const bottomMargin = doc.page.margins.bottom;
      doc.page.margins.bottom = 0;
      doc
        .fillColor("#999999")
        .fontSize(8)
        .font("Helvetica")
        .text(
          `Generated by ${definition.branding.systemName} on ${generatedAt}. Page ${i + 1} of ${range.count}`,
          50,
          doc.page.height - 35,
          { width: 495, align: "center", lineBreak: false },
        );
      doc.page.margins.bottom = bottomMargin;
    }
    doc.end();
  });
}

function renderTable(
  doc: PDFKit.PDFDocument,
  table: { headers: string[]; rows: string[][] },
  primary: string,
): void {
  const startX = 50;
  const usableWidth = 495;
  const columnWidth = usableWidth / table.headers.length;
  const rowHeight = 20;

  const drawRow = (cells: string[], y: number, isHeader: boolean) => {
    if (isHeader) {
      doc.rect(startX, y, usableWidth, rowHeight).fill(primary);
    }
    cells.forEach((cell, index) => {
      doc
        .fillColor(isHeader ? "#ffffff" : "#222222")
        .fontSize(9)
        .font(isHeader ? "Helvetica-Bold" : "Helvetica")
        .text(cell, startX + index * columnWidth + 4, y + 5, {
          width: columnWidth - 8,
          height: rowHeight,
          ellipsis: true,
        });
    });
  };

  let y = doc.y;
  drawRow(table.headers, y, true);
  y += rowHeight;
  for (const row of table.rows) {
    if (y > 760) {
      doc.addPage();
      y = 50;
      drawRow(table.headers, y, true);
      y += rowHeight;
    }
    doc.rect(startX, y, usableWidth, rowHeight).strokeColor("#dddddd").lineWidth(0.5).stroke();
    drawRow(row, y, false);
    y += rowHeight;
  }
  doc.y = y + 10;
  doc.x = startX;
}
